# Generated by cpp11: do not edit by hand

fun <- function() {
  invisible(.Call(`_slicr_fun`))
}

foo <- function(m, step, nc) {
  .Call(`_slicr_foo`, m, step, nc)
}

foo2 <- function(m, x, y) {
  .Call(`_slicr_foo2`, m, x, y)
}

foo3 <- function(m, step, nc) {
  .Call(`_slicr_foo3`, m, step, nc)
}
