# Generated by cpp11: do not edit by hand

run_slic <- function(m, vals, step, nc, con, output_type, type) {
  .Call(`_slicr_run_slic`, m, vals, step, nc, con, output_type, type)
}

a <- function(vals) {
  .Call(`_slicr_a`, vals)
}
